// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:62651fe5-97a3-493c-9b7c-a2c4b1130b7d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_QMRaX9Lzw",
    "aws_user_pools_web_client_id": "6j2ccrjn7n7g90n0le8r6dl2gn",
    "oauth": {}
};


export default awsmobile;
